# Generated by Django 6.0.6 on 2026-09-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0017_club_is_active_userregisterdb_current_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', models.JSONField(blank=True, default=list, help_text='Store multiple hotel image URLs')),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='Store amenities category-wise')),
                ('property_rules_info', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('aadhar_card', models.CharField(max_length=20, unique=True)),
                ('pan_card', models.CharField(max_length=20, unique=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='hotel_vendor/aadhar/')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='hotel_vendor/pan/')),
                ('bank_passbook_image', models.ImageField(blank=True, null=True, upload_to='hotel_vendor/bank/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=2)),
                ('cleanliness_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('location_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('service_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('value_for_money_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('facilities_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified_stay', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='myapp.userregisterdb')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('adults_qty', models.PositiveIntegerField(default=1)),
                ('room_images', models.JSONField(blank=True, default=list)),
                ('room_features', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "sq_ft": "250",\n            "view": "City View",\n            "bed": "King Bed",\n            "bathroom": "Private Bathroom"\n        }\n        ')),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('available_rooms', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.hotelvendor'),
        ),
        migrations.CreateModel(
            name='RoomPriceCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_name', models.CharField(max_length=255)),
                ('room_facilities', models.JSONField(blank=True, default=dict)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_carts', to='hotels.hotelroom')),
            ],
        ),
    ]
