# Generated by Django 6.0.6 on 2026-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
