# Generated by Django 6.0.6 on 2026-07-09 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200, unique=True)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_img', models.URLField(blank=True, max_length=1000, null=True)),
                ('profile_img_fileid', models.CharField(blank=True, max_length=200, null=True)),
                ('bike_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('bike_image_fileid', models.CharField(blank=True, max_length=200, null=True)),
                ('bike_brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bike_model', models.CharField(max_length=200, null=True)),
                ('manufacturing_year', models.DateField(blank=True, null=True)),
                ('vehichle_no', models.CharField(blank=True, max_length=200, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=200, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['nick_name'], name='users_nick_na_f61e84_idx'), models.Index(fields=['mobileno'], name='users_mobilen_b8def6_idx'), models.Index(fields=['last_seen'], name='users_last_se_f59089_idx')],
            },
        ),
    ]
