# Generated by Django 6.0.6 on 2026-07-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_comment_postmedia_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='ACCEPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='myapp.userregister')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='myapp.userregister')),
            ],
            options={
                'db_table': 'user_follows',
                'indexes': [models.Index(fields=['follower'], name='user_follow_followe_a0b992_idx'), models.Index(fields=['following'], name='user_follow_followi_eaf074_idx'), models.Index(fields=['status'], name='user_follow_status_48cb56_idx'), models.Index(fields=['created_at'], name='user_follow_created_744e51_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_relation')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to='myapp.userregister')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='myapp.userregister')),
            ],
            options={
                'db_table': 'user_blocks',
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_relation')],
            },
        ),
    ]
