# Generated by Django 6.0.6 on 2026-07-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_follow_userblock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserRegisterdb',
        ),
    ]
