# Generated by Django 6.0.6 on 2026-07-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_userregister_userregisterdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feed_entries', to='myapp.userregisterdb')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_entries', to='myapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='myapp.userregisterdb')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='myapp_userf_user_id_24dd21_idx'), models.Index(fields=['post'], name='myapp_userf_post_id_f7e5d0_idx'), models.Index(fields=['creator'], name='myapp_userf_creator_8e8558_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_feed_post')],
            },
        ),
    ]
