# Generated by Django 6.0.6 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
