# Generated by Django 6.0.6 on 2026-09-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_club_clubmessage_clubmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
