# Generated by Django 6.0.6 on 2026-09-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_clubjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_mode', models.CharField(choices=[('group', 'Group Trip'), ('solo', 'Solo Trip')], default='group', max_length=10)),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_photo', models.ImageField(blank=True, null=True, upload_to='trips/')),
                ('trip_note', models.TextField(blank=True, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('meetup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meetup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meetup_address', models.TextField(blank=True, null=True)),
                ('meetup_time', models.TimeField(blank=True, null=True)),
                ('trip_associated_with_club', models.BooleanField(default=False)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('trip_duration_days', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('free', 'Free'), ('split', 'Split'), ('paid', 'Paid')], default='free', max_length=10)),
                ('trip_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('included_feature', models.JSONField(blank=True, default=list)),
                ('payment_mode_split_include', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='myapp.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='myapp.userregisterdb')),
            ],
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('start_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_location_address', models.TextField(blank=True, null=True)),
                ('stop_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stop_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stop_location_address', models.TextField(blank=True, null=True)),
                ('end_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_location_address', models.TextField(blank=True, null=True)),
                ('flag_off_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='myapp.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
