# Generated by Django 6.0.6 on 2026-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200, unique=True)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img/')),
            ],
        ),
    ]
