# Generated by Django 6.0.6 on 2026-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
