# Generated by Django 6.0.6 on 2026-07-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_userregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
