# Generated by Django 6.0.6 on 2026-07-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_userregister_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bike_image',
            field=models.ImageField(null=True, upload_to='bike_progile_img/'),
        ),
    ]
