# Generated by Django 6.0.6 on 2026-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_userregister_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bike_brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='bike_model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='manufacturing_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='vehichle_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='bike_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='profile_img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
