# Generated by Django 6.0.6 on 2026-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_userregister_bike_brand_name_userregister_bike_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bike_image_fileid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='profile_img_fileid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
