# Generated by Django 6.0.6 on 2026-07-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_userregister_bike_image_fileid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
